title = "ScagRPC"
gitRepoUrl = "https://github.com/The-Axolotl-Sun/scag-rpc"
gitSourceBranch = "main"

changelog = true
classOrder = ["ScagRPC", "Presets"]

[docusaurus]
url = "https://scag.theaxolotlsun.com/"
baseUrl = "/"

[home]
enabled = true
includeReadme = true

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright © 2026 The Axolotl Sun. Built with Moonwave and Docusaurus"